# @format

branches:
  only:
    - master

os: linux
dist: focal
language: node_js
node_js:
  - 15

before_install:
  - npm --version

install:
  - npm install

jobs:
  include:
    - stage: travis
      script:
        - npm run travis
